// frameworks/react/src/App.jsx
import React, { Component } from 'react'
import './App.style.sass'

import { Store } from './store.js'

function _prevent ($evt) {
  $evt.preventDefault()
  $evt.stopPropagation()
}

const store = new Store()

class App extends Component {
  constructor () {
    super()

    this.state = {
      colors : Object.freeze(store.colors),
      amount : 100
    }

    this.syncData = this.syncData.bind(this)
    this.handleAdd = this.handleAdd.bind(this)
    this.handleShuffle = this.handleShuffle.bind(this)
    this.handleSort = this.handleSort.bind(this)
    this.handleSwap = this.handleSwap.bind(this)
    this.handleUpdateColor = this.handleUpdateColor.bind(this)
    this.handleDeleteColor = this.handleDeleteColor.bind(this)
    this.handleClear = this.handleClear.bind(this)
  }

  syncData () {
    this.setState({ ...this.state, colors: store.colors })
  }

  handleAdd (amount = 1) {
    store.appendColors(amount)
    this.syncData()
  }

  handleShuffle () {
    store.shuffleColors()
    this.syncData()
  }

  handleSort () {
    store.sortColorsById()
    this.syncData()
  }

  handleSwap (rows) {
    store.swapColors(rows)
    this.syncData()
  }

  handleUpdateColor (id) {
    store.updateColor(id)
    this.syncData()
  }

  handleDeleteColor (id) {
    store.deleteColor(id)
    this.syncData()
  }

  handleClear () {
    store.clearColors()
    this.syncData()
  }

  render () {
    const TableRows = this.state.colors.map(({ id, color: label, color }) => (
      <tr
        key={id}
        style={{ backgroundColor: color }}
        className='app-table-row'
      >
        {/* <!-- COLOR ID --> */}
        <td className='app-table-id'>
          <span
            className='app-table-label'
            style={{ padding: '6px' }}
          >
            {id}
          </span>
        </td>

        {/* <!-- COLOR LABEL --> */}
        <td
          className='app-table-cell'
        >
          <span className='app-table-label'>
            {label}
          </span>
        </td>

        {/* <!-- ACTION: UPDATE COLOR --> */}
        <td className='app-table-cell app-table-action'>

          <a
            href='#update'
            className='button__update pure-button app-button app-table-label'
            onClick={($evt) => { this.handleUpdateColor(id); _prevent($evt) }}
          >
            {/* <!-- button icon --> */}
            <svg
              xmlns='http://www.w3.org/2000/svg'
              viewBox='0 0 51.4 51.4'
              width='24'
              height='24'
            >
              <g fill='#fff'><path d='M1.7 25.2a1 1 0 0 0 1-1c0-6.065 4.935-11 11-11h24v8.964L51.4 12.2 37.7 2.236V11.2h-24a13.02 13.02 0 0 0-13 13 1 1 0 0 0 1 1zm38-19.036L48 12.2l-8.3 6.036V6.164zm10 20.036a1 1 0 0 0-1 1c0 6.065-4.935 11-11 11h-24v-8.964L0 39.2l13.7 9.964V40.2h24a13.02 13.02 0 0 0 13-13 1 1 0 0 0-1-1zm-38 19.036L3.4 39.2l8.3-6.036v12.072z' /></g>
            </svg>
          </a>
        </td>

        {/* <!-- ACTION: DELETE COLOR --> */}

        <td className='app-table-cell app-table-action'>
          <a
            href='#delete'
            className='button__delete pure-button app-button app-table-label'
            onClick={($evt) => { this.handleDeleteColor(id); _prevent($evt) }}
          >
            {/* <!-- button icon --> */}
            <svg
              xmlns='http://www.w3.org/2000/svg'
              viewBox='0 0 59 59'
              width='24'
              height='24'
            >
              <g fill='#fff'><path d='M29.5 51a1 1 0 0 0 1-1V17a1 1 0 1 0-2 0v33a1 1 0 0 0 1 1zm-10 0a1 1 0 0 0 1-1V17a1 1 0 1 0-2 0v33a1 1 0 0 0 1 1zm20 0a1 1 0 0 0 1-1V17a1 1 0 1 0-2 0v33a1 1 0 0 0 1 1zm13-45H38.456c-.1-1.25-.495-3.358-1.813-4.7C35.8.434 34.75 0 33.5 0h-10c-1.252 0-2.3.434-3.144 1.3-1.318 1.353-1.703 3.46-1.813 4.7H6.5a1 1 0 1 0 0 2h2.04l1.915 46.02c.037 1.722 1.1 4.98 4.908 4.98h28.272c3.8 0 4.87-3.257 4.907-4.958L50.46 8h2.04a1 1 0 1 0 0-2zM21.792 2.68C22.24 2.223 22.8 2 23.5 2h10c.7 0 1.26.223 1.708.68.805.823 1.128 2.27 1.24 3.32H20.553c.112-1.048.435-2.496 1.24-3.32zm24.752 51.3c-.006.3-.144 3.02-2.908 3.02H15.364c-2.734 0-2.898-2.717-2.9-3.042L10.542 8h37.915l-1.913 45.98z' /></g>
            </svg>
          </a>
        </td>
      </tr>
    ))

    return (
      <div id='app'>
        <header className='app-header app-u-fixed app-u-pin-t app-u-shadow-lg'>
          {/* <!-- APP MENU --> */}
          <div className='app-container app-menu pure-menu pure-menu-horizontal'>
            {/* <!-- BRAND: framework@version --> */}
            <span className='app-menu-heading pure-menu-heading app-title'>
              React
            </span>
          </div>

          {/* <!-- APP ACTIONS --> */}
          <div className='app-actions'>
            {/* <!-- GRID --> */}
            <div className='app-wrapper app-container'>
              {/* <!-- ADD COLOR --> */}
              <div className='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
                <button
                  id='button__add'
                  className='pure-button app-button'
                  style={{ backgroundColor: 'LimeGreen' }}
                  onClick={() => this.handleAdd(1)}
                >Inserir 1 Item</button>
              </div>

              {/* <!-- LOAD 50 COLORS --> */}
              <div className='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
                <button
                  id='button__populate'
                  className='pure-button app-button'
                  style={{ backgroundColor: 'DodgerBlue' }}
                  onClick={() => this.handleAdd(50)}
                >Inserir 50 Itens</button>
              </div>

              {/* <!-- SWAP 2 ROWS --> */}
              <div className='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
                <button
                  id='button__swap'
                  className='pure-button app-button'
                  style={{ backgroundColor: 'OrangeRed' }}
                  onClick={() => this.handleSwap([0, this.state.colors.length - 1])}
                >Permutar 2 Itens</button>
              </div>

              {/* <!-- SHUFFLE COLORS --> */}
              <div className='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
                <button
                  id='button__shuffle'
                  className='pure-button app-button'
                  style={{ backgroundColor: 'DarkViolet' }}
                  onClick={this.handleShuffle}
                >Embaralhar Lista</button>
              </div>

              {/* <!-- SORT COLORS-- > */}
              <div className='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
                <button
                  id='button__sort'
                  className='pure-button app-button'
                  style={{ backgroundColor: 'FireBrick' }}
                  onClick={this.handleSort}
                >Ordernar Lista</button>
              </div >

              {/* <!--CLEAR COLORS-- > */}
              <div className='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
                <button
                  id='button__clear'
                  className='pure-button app-button'
                  style={{ backgroundColor: 'Crimson' }}
                  onClick={this.handleClear}
                >Limpar Lista</button>
              </div >
            </div >
          </div >
        </header >

        {/* <!--APP TABLE-- > */}
        <div className='app-container app-table-wrapper' >
          <table className='app-table'>
            <tbody className='app-table-body'>

              {/* <!-- COLOR --> */}
              {TableRows}
            </tbody >
          </table >
        </div >
      </div >
    )
  }
}

export default App

// frameworks/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Store } from '../store';
const store = new Store();

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})

export class AppComponent {
  title = 'angular-benchmark';
  colors = Object.freeze(store.colors);
  amount = 100;

  prevent($evt) {
    $evt.stopPropagation();
    $evt.preventDefault();
  }

  add(amount = 1) {
    store.appendColors(amount);
    this.syncData();
  }

  shuffle() {
    store.shuffleColors();
    this.syncData();
  }

  sort() {
    store.sortColorsById();
    this.syncData();
  }

  swap(rows) {
    store.swapColors(rows);
    this.syncData();
  }

  updateColor(id) {
    store.updateColor(id);
    this.syncData();
  }

  deleteColor(id) {
    store.deleteColor(id);
    this.syncData();
  }

  clear() {
    store.clearColors();
    this.syncData();
  }

  syncData() {
    this.colors = Object.freeze(store.colors);
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<!-- ROOT TAG -->
<div id='app'>
  <header class='app-header app-u-fixed app-u-pin-t app-u-shadow-lg'>
    <!-- APP MENU -->
    <div class='app-container app-menu pure-menu pure-menu-horizontal'>
      <!-- BRAND: framework@version -->
      <span class='app-menu-heading pure-menu-heading app-title'>
        Angular
      </span>
    </div>

    <!-- APP ACTIONS -->
    <div class='app-actions'>
      <!-- GRID -->
      <div class='app-wrapper app-container'>
        <!-- ADD COLOR -->
        <div class='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
          <button id='button__add' class='pure-button app-button' style='background-color: LimeGreen' (click)='add(1)'>
            Inserir 1 Item
          </button>
        </div>

        <!-- LOAD 100 COLORS -->
        <div class='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
          <button id='button__populate' class='pure-button app-button' style='background-color: DodgerBlue' (click)='add(100)'>
            Inserir 100 Itens
          </button>
        </div>

        <!-- SWAP 2 ROWS -->
        <div class='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
          <button id='button__swap' class='pure-button app-button' style='background-color: OrangeRed' (click)='swap([0, colors.length - 1])'>
            Permutar 2 Itens
          </button>
        </div>

        <!-- SHUFFLE COLORS -->
        <div class='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
          <button id='button__shuffle' class='pure-button app-button' style='background-color: DarkViolet' (click)='shuffle()'>
            Embaralhar Lista
          </button>
        </div>

        <!-- SORT COLORS -->
        <div class='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
          <button id='button__sort' class='pure-button app-button' style='background-color: FireBrick' (click)='sort()'>
            Ordernar Lista
          </button>
        </div>

        <!-- CLEAR COLORS -->
        <div class='pure-u-12-24 pure-u-md-8-24 pure-u-xl-4-24'>
          <button id='button__clear' class='pure-button app-button' style='background-color: Crimson' (click)='clear()'>
            Limpar Lista
          </button>
        </div>
      </div>
    </div>
  </header>

  <!-- APP TABLE -->
  <div class='app-container app-table-wrapper'>
    <table class='app-table'>
      <tbody class='app-table-body'>
        <!-- COLOR -->
        <tr *ngFor='let color of colors' :key='`table-row-${coilor.id}-${color.color}`' [style.background-color]='color.color'
          class='app-table-row'>
          <!-- COLOR ID -->
          <td class='app-table-id'>
            <span class='app-table-label' style='padding: 6px'>
              {{ color.id }}
            </span>
          </td>

          <!-- COLOR LABEL -->
          <td class='app-table-cell'>
            <span class='app-table-label'>
              {{ color.color }}
            </span>
          </td>

          <!-- ACTION: UPDATE COLOR -->
          <td class='app-table-cell app-table-action'>
            <a href='#update' class='button__update pure-button app-button app-table-label' (click)='updateColor(color.id); prevent($event)'>
              <!-- button icon -->
              <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 51.4 51.4' width='24' height='24'>
                <g fill='#fff'>
                  <path d='M1.7 25.2a1 1 0 0 0 1-1c0-6.065 4.935-11 11-11h24v8.964L51.4 12.2 37.7 2.236V11.2h-24a13.02 13.02 0 0 0-13 13 1 1 0 0 0 1 1zm38-19.036L48 12.2l-8.3 6.036V6.164zm10 20.036a1 1 0 0 0-1 1c0 6.065-4.935 11-11 11h-24v-8.964L0 39.2l13.7 9.964V40.2h24a13.02 13.02 0 0 0 13-13 1 1 0 0 0-1-1zm-38 19.036L3.4 39.2l8.3-6.036v12.072z' />
                </g>
              </svg>
            </a>
          </td>

          <!-- ACTION: DELETE COLOR -->

          <td class='app-table-cell app-table-action'>
            <a href='#delete' class='button__delete pure-button app-button app-table-label' (click)='deleteColor(color.id); prevent($event)'>
              <!-- button icon -->
              <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 59 59' width='24' height='24'>
                <g fill='#fff'>
                  <path d='M29.5 51a1 1 0 0 0 1-1V17a1 1 0 1 0-2 0v33a1 1 0 0 0 1 1zm-10 0a1 1 0 0 0 1-1V17a1 1 0 1 0-2 0v33a1 1 0 0 0 1 1zm20 0a1 1 0 0 0 1-1V17a1 1 0 1 0-2 0v33a1 1 0 0 0 1 1zm13-45H38.456c-.1-1.25-.495-3.358-1.813-4.7C35.8.434 34.75 0 33.5 0h-10c-1.252 0-2.3.434-3.144 1.3-1.318 1.353-1.703 3.46-1.813 4.7H6.5a1 1 0 1 0 0 2h2.04l1.915 46.02c.037 1.722 1.1 4.98 4.908 4.98h28.272c3.8 0 4.87-3.257 4.907-4.958L50.46 8h2.04a1 1 0 1 0 0-2zM21.792 2.68C22.24 2.223 22.8 2 23.5 2h10c.7 0 1.26.223 1.708.68.805.823 1.128 2.27 1.24 3.32H20.553c.112-1.048.435-2.496 1.24-3.32zm24.752 51.3c-.006.3-.144 3.02-2.908 3.02H15.364c-2.734 0-2.898-2.717-2.9-3.042L10.542 8h37.915l-1.913 45.98z' />
                </g>
              </svg>
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
